### ISSUE TITLE
Adding this package to https://packagist.org/

### ISSUE THREAD

**Issue by IonelLupu** [arquivei/laravel-prometheus-exporter#22]
Is it possible to add this package to packagist.org? 

We are using a gitlab runner to install our dependencies and it seems we need to create a special account for it on Github to be able to install the package. This is because installing it (using composer) without an account throws an error `GitHub API limit (60 calls/hr) is exhausted, could not fetch https://api.github.com/repos/arquivei/laravel-prometheus-exporter. Create a GitHub OAuth token to go over the API rate limit. You can also wait until 2021-09-06 10:26:57 for the rate limit to reset.`

Having this package on Packagist will make make our lives easier 😄

**Comment by fcoedno** [comment]
It is already on packagist: https://packagist.org/packages/arquivei/laravel-prometheus-exporter

**Comment by IonelLupu** [comment]
Ah. Ok. Sorry. I thought it wasn't. Because the Readme says we need to add:
```json
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/arquivei/laravel-prometheus-exporter"
  }
],
```
 Which means it will install it from Github directly and not from packagist. I think you can remove this section from the Readme, right?

Anyways, I installed it without that and it worked. Thank you! 😄
