### ISSUE TITLE
Support Laravel / Lumen 7.0

### ISSUE THREAD

**Issue by ddzobov** [arquivei/laravel-prometheus-exporter#7]

**Comment by mizan3008** [comment]
I am trying to install this package one of my laravel 8 application, but getting this error:

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - endclothing/prometheus_client_php 1.0.x-dev requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - arquivei/laravel-prometheus-exporter dev-master requires endclothing/prometheus_client_php ^1.0.2 || 1.0.x-dev -> satisfiable by endclothing/prometheus_client_php[1.0.x-dev].
    - Installation request for arquivei/laravel-prometheus-exporter dev-master as 1.3 -> satisfiable by arquivei/laravel-prometheus-exporter[dev-master].
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.0, 7.1.1, 7.1.x-dev].
